from __future__ import annotations

import argparse
import itertools
import random
from pathlib import Path

from PIL import Image

from nft_asset_toolbox.core import (
    discover_trait_layers,
    validate_collection,
    write_trait_frequency_csv,
    write_validation_report_csv,
)

CANONICAL_TRAIT_ORDER = ["Background", "Body", "Head", "Eyes", "Accessory"]
IMAGE_SIZE = 512
RANDOM_SEED = 42


def _ordered_traits(layers: dict[str, list[Path]]) -> list[str]:
    ordered = [name for name in CANONICAL_TRAIT_ORDER if name in layers]
    ordered += [name for name in sorted(layers) if name not in ordered]
    return ordered


def _all_combinations(layers: dict[str, list[Path]], trait_order: list[str]) -> list[tuple[tuple[str, Path], ...]]:
    per_trait = [[(trait, path) for path in layers[trait]] for trait in trait_order]
    return list(itertools.product(*per_trait))


def _composite(combo: tuple[tuple[str, Path], ...]) -> Image.Image:
    base = None
    for _trait, path in combo:
        layer = Image.open(path).convert("RGBA")
        if base is None:
            base = layer
        else:
            base = Image.alpha_composite(base, layer)
    return base.resize((IMAGE_SIZE, IMAGE_SIZE), Image.LANCZOS)


def generate_sample_collection(
    collection_dir: Path,
    count: int = 100,
    seed: int = RANDOM_SEED,
) -> dict:
    collection_dir = Path(collection_dir)
    layers = discover_trait_layers(collection_dir)
    if not layers:
        raise SystemExit(
            f"No trait layer folders found under {collection_dir} "
            f"(expected one of: {', '.join(('sample_assets', 'layers'))})"
        )

    trait_order = _ordered_traits(layers)
    combos = _all_combinations(layers, trait_order)

    rng = random.Random(seed)
    rng.shuffle(combos)
    count = min(count, len(combos))
    selected = combos[:count]

    images_dir = collection_dir / "output" / "images"
    metadata_dir = collection_dir / "output" / "metadata"
    images_dir.mkdir(parents=True, exist_ok=True)
    metadata_dir.mkdir(parents=True, exist_ok=True)

    for token_id, combo in enumerate(selected, start=1):
        image = _composite(combo).convert("RGB").convert("P", palette=Image.ADAPTIVE, colors=256)
        image.save(images_dir / f"{token_id}.png", optimize=True)

        attributes = [{"trait_type": trait, "value": path.stem} for trait, path in combo]
        metadata = {
            "name": f"Sample NFT #{token_id}",
            "description": "Sample collection asset generated by NFT Asset Toolbox.",
            "image": f"ipfs://PLACEHOLDER/{token_id}.png",
            "attributes": attributes,
        }
        metadata_path = metadata_dir / f"{token_id}.json"
        metadata_path.write_text(_dump_json(metadata), encoding="utf-8")

    result = validate_collection(collection_dir / "output")

    reports_dir = collection_dir / "reports"
    trait_csv = write_trait_frequency_csv(result, reports_dir / "trait_frequency.csv")
    validation_csv = write_validation_report_csv(result, reports_dir / "validation_report.csv")

    return {
        "trait_folders": len(layers),
        "source_assets": sum(len(v) for v in layers.values()),
        "possible_combinations": len(combos),
        "generated_count": count,
        "images_dir": images_dir,
        "metadata_dir": metadata_dir,
        "trait_csv": trait_csv,
        "validation_csv": validation_csv,
        "validation_ok": result.ok,
        "trait_count": result.trait_count,
    }


def _dump_json(data: dict) -> str:
    import json

    return json.dumps(data, indent=2) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate a demo NFT collection from sample_assets/ layers.")
    parser.add_argument("--collection-dir", default="sample_collection", type=Path)
    parser.add_argument("--count", default=100, type=int)
    parser.add_argument("--seed", default=RANDOM_SEED, type=int)
    args = parser.parse_args()

    summary = generate_sample_collection(args.collection_dir, count=args.count, seed=args.seed)

    print("Sample collection generated:")
    print(f"  Trait folders:          {summary['trait_folders']}")
    print(f"  Source layer assets:    {summary['source_assets']}")
    print(f"  Possible combinations:  {summary['possible_combinations']}")
    print(f"  Generated NFTs:         {summary['generated_count']}")
    print(f"  Images:                 {summary['images_dir']}")
    print(f"  Metadata:               {summary['metadata_dir']}")
    print(f"  Trait report:           {summary['trait_csv']}")
    print(f"  Validation report:      {summary['validation_csv']}")
    print(f"  Validation status:      {'PASS' if summary['validation_ok'] else 'FAIL'}")


if __name__ == "__main__":
    main()
